environment:
  name: test
  project: cdf-bootcamp-39-test # ex. cdf-bootcamp-01-test
  type: test # prod, staging, dev, test, qa
  selected:
  - modules/bootcamp/data_foundation
  - modules/bootcamp/ice_cream_api
  - modules/bootcamp/use_cases/oee
variables:
  modules:
    bootcamp:
      CDF_PROJECT: cdf-bootcamp-39-test # ex. cdf-bootcamp-01-test
      IDP_CLIENT_ID: ${IDP_CLIENT_ID} # replaced by .env
      IDP_CLIENT_SECRET: ${IDP_CLIENT_SECRET} # replaced by .env
      IDP_TENANT_ID: ${IDP_TENANT_ID} # replaced by .env
      CDF_URL: https://westeurope-1.cognitedata.com # This is related to the cluster where the CDF project is hosted.
      IDP_SCOPES: https://westeurope-1.cognitedata.com/.default
      IDP_TOKEN_URL: ${IDP_TOKEN_URL} # replaced by .env

      # Groups
      data_developer_source_id: eefd284d-37f0-4057-8c96-0cf3af899639 # ex. xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxx
      data_pipeline_oee_source_id: b31d5391-becb-4211-bf71-8e57c83c239e # ex. xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxx
      readwrite_source_id: 44ffecc2-3b3f-4bd5-9628-aafaf2fe35db  # ex. xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxx
      readonly_source_id: 44ffecc2-3b3f-4bd5-9628-aafaf2fe35db  # ex. xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxx
      icapi_extractors_source_id: f309de72-2e80-401c-8b87-2453a883b43f # ex. xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxx

      # Client Ids
      data_pipeline_oee_client_id: ${DATA_PIPELINE_OEE_CLIENT_ID} # replaced by .env
      data_pipeline_oee_client_secret: ${DATA_PIPELINE_OEE_CLIENT_SECRET} # replaced by .env

      icapi_extractors_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID} # replaced by .env
      icapi_extractors_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET} # replaced by .env

      icapi_ds_external_id: ds_icapi
      use_cases:
        oee:
          uc_oee_ds_external_id: ds_uc_oee
